# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        config_full:
            toolbar: full
            filebrowserUploadUrl: '/admin/upload-image'
            filebrowserUploadMethod: 'form'
            # Pour simplifier l'upload d'image
            filebrowserImageUploadUrl: '/admin/upload-image'
            extraPlugins: "uploadimage"
            # Supprimer les onglets avancés de la boîte de dialogue
            removeDialogTabs: 'image:advanced;image:Link'
            # Permettre l'upload par drag & drop
            uploadUrl: '/admin/upload-image'