vich_uploader:
    db_driver: orm

    mappings:
        images_mosquee:
            uri_prefix: uploads/images/mosquee
            upload_destination: '%kernel.project_dir%/public/uploads/images/mosquee'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
